
<?php

function GetProductData() {
    return '[
        {
            "title": "Barva na obočí, 20ml",
            "id": "barva-na-oboci-20ml",
            "price": "349",
            "categories": "[]",
            "manufacturer": "beautiful-brows",
            "descriptionShort": "<p>Na výběr různé druhy odstínů.</p>",
            "description": "<p>Intenzivní krémová barva na obočí <strong>odstín NATURAL</strong> (studený odstín) pro dosažení přirozené barvy obočí. Míchání spolu s 3% krémovým peroxidem.<br />Barvy jsou určeny k profesionálnímu i domácímu použití. Vyvážená kombinace pečlivě vybraných pečujících složek, jako je lanolin, nebo slunečnicový olej zaručuje bezpečnou aplikaci, která jde ruku v ruce se současnými kosmetickými trendy v péči o obočí, řasy i pokožku. <br /><strong>Odstín doporučujeme pro:</strong> všechny odstíny blond, zrz, světle hnědé vlasy.</p><p><strong><em>Jak použít</em></strong><br />Podrobný návod je součástí každého balení. K aktivaci barvy je zapotřebí použít výhradně krémový aktivátor barvy s 3% peroxidem Beautiful Brows.</p><p><strong>Upozornění</strong>: barva může způsobit alergické reakce, proto před prvním použitím proveďte test snášenlivosti. Při barvení používejte rukavice. <strong>Tento produkt není vhodný pro osoby mladší 16 let.</strong></p><p><strong>Nebarvěte si obočí pokud:</strong></p><ul><li>Máte vyrážku v obličeji, citlivou, podrážděnou nebo poraněnou pokožku.</li><li>Pokud jste prodělala v minulosti alergickou reakci v důsledku barvení řas nebo obočí.</li><li>Pokud jste prodělala v minulosti alergickou reakci na dočasné tetování hennou.</li></ul>",
            "image": "BeatifulBorows/barvaNaOboci-natural.png",
            "additionalImages": "[\"BeatifulBorows/barvaNaOboci-tmaveHneda.png\",\"BeatifulBorows/barvaNaOboci-intenzivniCerna.png\",\"BeatifulBorows/barvaNaOboci-modroCerna.png\",\"BeatifulBorows/barvaNaOboci-svetleHneda.png\"]",
            "variants": "[{\"title\":\"světle hnědá\", \"stockStatus\": \"skladem\"}, {\"title\":\"tmavě hnědá\", \"stockStatus\": \"skladem\"}, {\"title\":\"intenzivní černá\", \"stockStatus\": \"skladem\"}, {\"title\":\"modro-černá\", \"stockStatus\": \"skladem\"}]",
            "specifications": "",
            "published": "1",
            "created": "2022-02-27 16:04:38",
            "stockStatus": "skladem"
          },
          {
            "title": "Krémový aktivátor barvy, 100ml",
            "id": "kremovy-aktivator-barvy-100ml",
            "price": "299",
            "categories": "[]",
            "manufacturer": "beautiful-brows",
            "descriptionShort": "<p>Krémový aktivátor barvy s 3% peroxidem určený pro profesionální použití pro barvení řas a obočí.</p>",
            "description": "<p>Krémový aktivátor barvy s 3% peroxidem určený pro profesionální použití pro barvení řas a obočí.</p><p><strong>Jak použít:</strong> smíchejte 1 cm barvy pro obočí a řasy Beautiful Brows s na objem stejným množství krémového aktivátoru.</p><p><strong>Upozornění:</strong> obsahuje Hydrogen Peroxide. Použijte rukavice. Vyvarujte se kontaktu s očima a s pokožkou, v případě zasažení okamžitě vypláchněte vodou. Pokud podráždění přetrvává, vyhledejte lékařskou pomoc. Uchovávejte mimo dosah dětí. Pouze pro barvení řas a obočí. Pouze pro vnější použití. Uchovávejte na suchém a chladném místě ve vzpřímené poloze.</p>",
            "image": "BeatifulBorows/keromovyAktivatorBarvy.png",
            "additionalImages": "",
            "variants": "",
            "specifications": "",
            "published": "1",
            "created": "2022-02-27 20:32:19",
            "stockStatus": "skladem"
          },
          {
            "title": "Štěteček na barvu, 9,5cm ",
            "id": "stetecek-na-barvu-9-5cm-2",
            "price": "120",
            "categories": "[]",
            "manufacturer": "beautiful-brows",
            "descriptionShort": "<p>Štěteček pro dokonalé nanášení barvy Beautiful Brows &amp; Lashes a definici tvaru obočí.</p>",
            "description": "<p>Štěteček pro dokonalé nanášení barvy Beautiful Brows &amp; Lashes a definici tvaru obočí.</p>",
            "image": "BeatifulBorows/stetecekNaBarvu.png",
            "additionalImages": "",
            "variants": "",
            "specifications": "",
            "published": "1",
            "created": "2022-02-27 20:34:06",
            "stockStatus": "skladem"
          },
          {
            "title": "Kalíšek na míchání barvy – skleněný, 15ml",
            "id": "kalisek-na-michani-barvy-skleneny-15ml",
            "price": "69",
            "categories": "[]",
            "manufacturer": "beautiful-brows",
            "descriptionShort": "<p>Skleněný kalíšek je ideální pro míchání barvy. Má robustní dno, takže se nepřevrhne.</p>",
            "description": "<p>Skleněný kalíšek je ideální pro míchání barvy. Má robustní dno, takže se nepřevrhne.</p>",
            "image": "BeatifulBorows/kalisekNaBarvu.png",
            "additionalImages": "",
            "variants": "",
            "specifications": "",
            "published": "1",
            "created": "2022-02-27 20:35:07",
            "stockStatus": "skladem"
          },
          {
            "title": "Duo sada na úpravu a barvení obočí",
            "id": "duo-sada-na-upravu-a-barveni-oboci",
            "price": "1290",
            "categories": "[]",
            "manufacturer": "beautiful-brows",
            "descriptionShort": "<p><strong>Pro barvu vlasů:</strong> světlá blond (teplý i studený odstín), oříškově hnědá, medová, špinavá blond, světle až tmavě hnědá, zrz.</p>",
            "description": "<p>doporučujeme pro:<br /><strong>Barva vlasů:</strong> světlá blond (teplý i studený odstín), oříškově hnědá, medová, špinavá blond, světle až tmavě hnědá, zrz.</p><p><strong>TIP:</strong> dokonale překryje vybledlé tetování a dodá přirozenější vzhled.<br />Toužíte po dokonalém obočí, přirozené barvě a perfektním tvaru? To vše hravě zvládnete s domácí sadou Beautiful Brows.</p><p><strong>Vhodná pro:</strong> všechny typy pleti, pro každé obočí – řídké, husté, krátké, s jizvou, tetované, i naprosto bez chloupků.</p><p><strong>Barva je VODĚ, POTU a OTĚRU ODOLNÁ</strong> (sauna, bazén, sport)</p><p>O dokonalou barvu se postará zapékaný <strong>minerální pudr,</strong> který je <strong>vodě, potu a otěru odolný.</strong> Perfektního tvaru dosáhnete díky šablonám a pinzetě broušené laserem a jistě oceníte i kvalitní štětce, super rozjasňovač a praktické zrcátko.</p><p><strong>Propracováno do posledního detailu</strong>: elegantní a praktický design, jednotlivé části se dají pohodlně vyndat (oceníte při cestování). Když vypotřebujete, stačí jen dokoupit potřebnou část a sada je opět kompletní.</p><p><strong>Sada vydrží až 2 roky při každodenním používání.</strong><br />Dokonalé obočí Vás tak stojí 1,76 Kč na den a to je něco.</p><p><strong>Jak použít</strong><br />Vyberte jednu ze 6ti šablon, přiložte na Vaše obočí tak, aby co nejvíce chloupků prostupovalo skrz, širší stranou štětce naneste proti směru růstu chloupků barvu pohybem tam a zpět. Šablonu přetočte a zopakujte na druhém obočí. V případě potřeby doupravte zkosenou stranou štětce nebo vatovou tyčinkou. Za 10 minut barva zaschne a stane se vodě, potu a otěru odolná.</p>",
            "image": "BeatifulBorows/duoSadaNaUpravuOboci-lightBrown.png",
            "additionalImages": "[\"BeatifulBorows/duoSadaNaUpravuOboci-darkBrownChoco.png\",\"BeatifulBorows/duoSadaNaUpravuOboci-slateBlack.png\"]",
            "variants": "[{\"title\":\"light / medium\", \"stockStatus\": \"skladem\"},{\"title\":\"dark brown / choco\", \"stockStatus\": \"skladem\"},{\"title\":\"slate / black\", \"stockStatus\": \"skladem\"}]",
            "specifications": "",
            "published": "1",
            "created": "2022-02-27 20:43:03",
            "stockStatus": "skladem"
          },
          {
            "title": "Duo minerální pigment na obočí",
            "id": "duo-mineralni-pigment-na-oboci",
            "price": "420",
            "categories": "[]",
            "manufacturer": "beautiful-brows",
            "descriptionShort": "<p>Pro barvy vlasů: světlá blond (teplý i studený odstín), oříškově hnědá, medová, špinavá blond, světle až tmavě hnědá, zrz.</p>",
            "description": "<p>doporučujeme pro:<br /><strong>Barva vlasů:</strong> světlá blond (teplý i studený odstín), oříškově hnědá, medová, špinavá blond, světle až tmavě hnědá, zrz.</p><p><strong>TIP:</strong> dokonale překryje vybledlé tetování a dodá přirozenější vzhled.<br />Toužíte po dokonalém obočí, přirozené barvě a perfektním tvaru? To vše hravě zvládnete s domácí sadou Beautiful Brows.</p><p>Dochází Vám oblíbený barevný odstín v sadě Beautiful Brows? Změnila jste výrazně barvu vlasů? Právě pro Vás je tu náhradní náplň – barva na obočí, kterou jednoduše doplníte do Vaší sady a bude Vám opět dlouho sloužit.<strong> Až 2 roky při každodenním používání.</strong></p><p><strong>Vhodná pro:</strong> všechny typy pleti, pro každé obočí – řídké, husté, krátké, s jizvou, tetované, i naprosto bez chloupků.</p><p>Maximální účinnost díky speciální výrobní metodě – pudr je zapékán na více jak 900 °C, čímž je zaručena stabilita a výdrž produktu.</p><p><strong>TIP VIZÁŽISTY</strong>: Barva obočí by měla ladit s barvou vlasů. Obočí může být o odstín tmavší, ne však světlější. Pamatujte, že obočí je rámem obličeje.</p><p><strong>Barva je VODĚ, POTU a OTĚRU ODOLNÁ</strong> (sauna, bazén, sport)</p><p><em><strong>Jak použít</strong></em><br />Vyberte jednu ze 6ti šablon, přiložte na Vaše obočí tak, aby co nejvíce chloupků prostupovalo skrz, širší stranou štětce naneste proti směru růstu chloupků barvu pohybem tam a zpět. Šablonu přetočte a zopakujte na druhém obočí. V případě potřeby doupravte zkosenou stranou štětce nebo vatovou tyčinkou. Za 10 minut barva zaschne a stane se vodě, potu a otěru odolná.</p>",
            "image": "BeatifulBorows/mineralniPigmentNaOboci-lightMedium.png",
            "additionalImages": "[\"BeatifulBorows/mineralniPigmentNaOboci-darkBrownChoco.png\",\"BeatifulBorows/mineralniPigmentNaOboci-slateBlack.png\"]",
            "variants": "[{\"title\":\"light / medium\", \"stockStatus\": \"skladem\"},{\"title\":\"brown / choco\", \"stockStatus\": \"skladem\"},{\"title\":\"slate / black\", \"stockStatus\": \"skladem\"}]",
            "specifications": "",
            "published": "1",
            "created": "2022-02-27 20:58:48",
            "stockStatus": "skladem"
          },
          {
            "title": "Duo náhradní rozjasňovač ",
            "id": "duo-nahradni-rozjasnovac",
            "price": "420",
            "categories": "[]",
            "manufacturer": "beautiful-brows",
            "descriptionShort": "",
            "description": "<p><strong>DUO Rozjasňovač rozzáří a podtrhne dokonalý tvar obočí.</strong><br />Oko opticky zvětší, dodá mu jiskru a omladí celkový výraz obličeje.<br />Dochází Vám oblíbený rozjasňovač v sadě Beautiful Brows? Právě pro Vás je tu nová DUO náhradní náplň, kterou jednoduše doplníte do Vaší sady a bude Vám opět dlouho sloužit.</p><p><strong>Jak použít</strong><br />Nanáší se speciálním štětečkem, který je součástí Sady na úpravu a barvení obočí Beautiful Brows.<br />Aplikujte pod obočí – pro zvýraznění dokonalého tvaru obočí.</p><p><strong>TIP VIZÁŽISTY:</strong> Lze použít jako oční stín – ideální pro nositelky brýlí, nebo pro ženy, kterým padá horní pohyblivé víčko. Duo náhradní rozjasňovač.</p>",
            "image": "BeatifulBorows/mineralniPigmentNaOboci-rozjasnovac.png",
            "additionalImages": "",
            "variants": "",
            "specifications": "",
            "published": "1",
            "created": "2022-02-27 21:00:33",
            "stockStatus": "skladem"
          },
          {
            "title": "Šablony na obočí – 6 typů ",
            "id": "sablony-na-oboci-6-typu",
            "price": "330",
            "categories": "[]",
            "manufacturer": "beautiful-brows",
            "descriptionShort": "<p>6 Typů šablon pro vytvoření dokonalého tvaru.</p>",
            "description": "<p><strong>6 Typů šablon pro vytvoření dokonalého tvaru.</strong></p><p>Šablony se přizpůsobí každému tvaru obočí a dodají obličeji výraz.</p><p><strong>Jak použít:</strong> Zvolenou šablonu přiložte na Vaše obočí, snažte se umístit tak, aby co nejvíce chloupků prostupovalo šablonou a nejvyšší bod šablony byl umístěn v nejvyšším bodě Vašeho obočí a pevně přidržte.</p><p><strong>Sleek</strong> (Sleek Straight) = tenké, ale zároveň přirozené obočí s kulatým a (ostrým) začátkem.<br /><strong>Natural</strong> (Natural Straight) = přirozeně bohaté obočí s kulatým a (ostrým) začátkem.<br /><strong>Bold</strong> (Bold Straight) = krásně klenuté obočí s kulatým a (ostrým) začátkem.</p><p><strong>TIP VIZÁŽISTY:</strong> Nosíte brýle na blízko a nejste schopna se bez brýlí nalíčit? Vyberte šablonu, zastrčte za brýle a během pár vteřin je hotovo.</p>",
            "image": "BeatifulBorows/sablonyNaOboci.png",
            "additionalImages": "",
            "variants": "",
            "specifications": "",
            "published": "1",
            "created": "2022-02-27 21:02:26",
            "stockStatus": "skladem"
          },
          {
            "title": "Sérum loom Suprême se šnecím extraktem",
            "id": "serum-loom-supreme-se-snecim-extraktem",
            "price": "1290",
            "categories": "[]",
            "manufacturer": "bioearth",
            "descriptionShort": "",
            "description": "<p><em>Popis</em><br />Sérum na tvář nejnovější generace pro ošetření pokožky vykazující první známky stárnutí. Obohacený o komplex oligopeptidů získávaných ze semen okra (Hibiscus aesculentus), kontrastuje tvorbu známek stárnutí s tenzorovým efektem. Aplikuje se před krémem a zanechává pokožku viditelně hladkou a hydratovanou.</p><p><em>Funkční látky</em><br />Mikrofiltrovaný extrakt ze šnečího slizu (95%), extrakt z ibišku, kyselina hyaluronová, ženšen *, měsíček *, řebříček *, výtažek z hamamelu *</p><p><br />* z ekologického zemědělství </p><p><br /><em>Jak používat</em><br />Aplikujte pár kapek na obličej a krk a lehce zaťupkejte prsty. Můžete ráno a večer. Toto sérum se může používat celoročně. Ostatní pouze podzim – zima.</p><p><em>Ingredience</em><br />Acqua (voda), filtrovaná hlemýžďová sekrece, celulózová guma, hydrolyzovaný extrakt z ibišku esculentus, hyaluronát sodný, gel z aloe barbadensis *(šťáva z listů aloe barbadensis *), extrakt z květu měsíčku lékařského *, extrakt z achillea millefolium *, list hamamelis virginiana (Vilín virginský) extrakt *, extrakt z kořene ženšenu panax *, dextrin, glycerin, kyselina citronová, fenethylalkohol, kaprylylglykol. </p><p><br />* z ekologického zemědělství.</p>",
            "image": "Biohearth/Serum_loom_Supreme_se_snecim_extraktem.jpg",
            "additionalImages": "",
            "variants": "",
            "specifications": "[{\"title\":\"mnozstvi\",\"value\":\"30 ml\"}]",
            "published": "1",
            "created": "2022-03-06 12:27:51",
            "stockStatus": "skladem"
          },
          {
            "title": "Sérum na obličej proti stárnutí, 5 ml",
            "id": "serum-na-oblicej-proti-starnuti-5-ml",
            "price": "220",
            "categories": "[]",
            "manufacturer": "bioearth",
            "descriptionShort": "",
            "description": "<p><em>Jak používat</em><br />Naneste několik kapek séra na obličej a jemně masírujte, dokud se úplně nevstřebá. Na to naneste oblíbený denní krém. Séra jsou koncentráty účinných látek, proto s nimi šetřete. Používají se 1x týdně v období podzim až zima (vyjma sér ze šnečích extraktů, ty se mohou používat celoročně).</p><p><br />* z ekologického zemědělství </p><p><br /><em>Ingredience</em><br />Aqua , Aloe Barbadensis Leaf Juice*, Sodium Hyaluronate, Calendula officinalis flower extract*, CHAMOMILLA RECUTITA (MATRICARIA) FLOWER EXTRACT*, HAMAMELIS VIRGINIANA (WITCH HAZEL) LEAF EXTRACT*, Glycerin, Cellulose gum, PHENETHYL ALCOHOL, Caprylyl Glycol.</p><p><br />*Suroviny z ekologického zemědělství.</p>",
            "image": "Biohearth/Serum_na_oblicej_proti_starnuti.jpg",
            "additionalImages": "",
            "variants": "",
            "specifications": "[{\"title\":\"mnozstvi\",\"value\":\"5 ml\"}]",
            "published": "1",
            "created": "2022-03-06 12:31:28",
            "stockStatus": "skladem"
          },
          {
            "title": "Epigenetická liftingová maska ​​na obličej s kmenovými buňkami",
            "id": "epigeneticka-liftingova-maska-na-oblicej-s-kmenovymi-bunkami",
            "price": "220",
            "categories": "[]",
            "manufacturer": "bioearth",
            "descriptionShort": "",
            "description": "<p>Účinná jednorázová maska ​​na obličej z celulózy pro jemné kosmetické ošetření s vyhlazujícím efektem. Formulováno s inovativními přísadami, jako je epigenetický komplex, Platechonův biotechnologický extrakt, arganové kmenové buňky a rajčatová šťáva Fiaschetto (přísada podporující biologickou rozmanitost), které díky synergii působí, že pokožka vypadá mladší a uvolněnější. Obsahuje šťávu z aloe vera a extrakt z Jania Rubens.</p><p><br /><em>Funkční látky</em><br />Aloe Vera Juice *, Jania Rubens Extract, Tomato Extract, Kyselina hyaluronová, Panama Wood Extract, Kigelia Africana Extract, Granátové jablko extrakt *, Réva extrakt *, Fermenty, Arganové kmenové buňky. </p><p>* z ekologického zemědělství</p><p><br /><em>Jak používat</em><br />Masku naneste na důkladně očištěný a suchý obličej, nechte působit 15–20 minut. Sundejte masku a masírujte zbytkovou tekutinu, dokud se nevstřebá. Ošetření dokončete nanesením několika kapek odpovídajícího pleťového séra. </p><p><em>Ingrediece</em><br />Aqua, Aloe Barbadensis Leaf Juice*, Propanediol, HYDROLYZED TOMATO SKIN, Hydrolyzed Hyaluronic Acid, SORBITOL, QUILLAJA SAPONARIA BARK EXTRACT, SOLANUM LYCOPERSICUM FRUIT JUICE*, KIGELIA AFRICANA FRUIT EXTRACT, PUNICA GRANATUM FRUIT EXTRACT*, Vitis Vinifera Fruit Extract*, MALTODEXTRIN, ALTEROMONAS FERMENT EXTRACT, ORIGANUM MAJORANA LEAF EXTRACT, Argania spinosa callus culture extract, Jania Rubens Extract, ISOMALT, Benzyl Alcohol, POLYGLYCERYL-4 CAPRATE, Xanthan Gum, Glycerin, EthylhexylGlycerin, **PARFUM, TETRASODIUM GLUTAMATE DIACETATE, Citric Acid, PHENETHYL ALCOHOL, Sodium Benzoate, potassium sorbate, Lecithin.</p><p><br /><strong>*Suroviny z ekologického zemědělství.</strong></p><p><br /><strong>**Bioearth ve svých produktech používá výhradně přírodní vůně = parfémy bez chemických látek, získané z éterických olejů. Jedná se tedy o vůně, které nevyvolávají alergické reakce.</strong></p>",
            "image": "Biohearth/Epigeneticka_liftingova_maska_na_oblicej_s_kmenovymi_bunkami.jpg",
            "additionalImages": "",
            "variants": "",
            "specifications": "[{\"title\":\"mnozstvi\",\"value\":\"15 ml\"}]",
            "published": "1",
            "created": "2022-03-13 10:48:38",
            "stockStatus": "skladem"
          },
          {
            "title": "Povzbuzující hydratační maska ​​na obličej s jablečnou šťávou",
            "id": "povzbuzujici-hydratacni-maska-na-oblicej-s-jablecnou-stavou",
            "price": "220",
            "categories": "[]",
            "manufacturer": "bioearth",
            "descriptionShort": "",
            "description": "<p>Jednorázová maska ​​na obličej z celulózy navržená tak, aby poskytovala intenzivní pocit hydratace díky přítomnosti damašské růžové vody a růžové jablečné šťávy, což je přísada podporující biologickou rozmanitost. Po aplikaci vypadá pokožka obličeje svěží a mladá. Obsahuje šťávu z aloe vera a extrakt z Jania Rubens.</p><p><em>Funkční látky</em><br />Aloe Vera Juice *, Jania Rubens Extract, Damask Rose Water *, Rosa Centifolia Water, Rosehip Extract, Apple Juice **.</p><p><em>Jak používat</em><br />Masku naneste na důkladně očištěný a suchý obličej, nechte působit 15–20 minut. Sundejte masku a masírujte zbytkovou tekutinu, dokud se nevstřebá. Ošetření dokončete nanesením několika kapek odpovídajícího pleťového séra. </p><p><em>Ingrediece</em><br />Aqua, Aloe Barbadensis Leaf Juice*, ROSA DAMASCENA FLOWER WATER*, Propanediol, ROSA CENTIFOLIA FLOWER WATER, ROSA CANINA FRUIT EXTRACT, Pyrus Malus Juice**, Actinidia Chinensis Fruit Extract*, Jania Rubens Extract, Ferulic Acid, POLYGLYCERYL-4 CAPRATE, Xanthan Gum, Glycerin, TOCOPHERYL ACETATE, Benzyl Alcohol, EthylhexylGlycerin, **PARFUM, TETRASODIUM GLUTAMATE DIACETATE, potassium sorbate, Sodium Benzoate, Benzyl Alcohol, Phenoxyethanol.</p><p><strong>*Suroviny z ekologického zemědělství.</strong></p><p><strong>**Bioearth ve svých produktech používá výhradně přírodní vůně = parfémy bez chemických látek, získané z éterických olejů. Jedná se tedy o vůně, které nevyvolávají alergické reakce.</strong></p>",
            "image": "Biohearth/Povzbuzujici_hydratacni_maska_na_oblicej_s_jablecnou_stavou.jpg",
            "additionalImages": "",
            "variants": "",
            "specifications": "[{\"title\":\"mnozstvi\",\"value\":\"15 ml\"}]",
            "published": "1",
            "created": "2022-03-13 10:51:39",
            "stockStatus": "skladem"
          },
          {
            "title": "Loom plátýnková maska ​​na obličej se šnečím extraktem - jednorázová maska",
            "id": "loom-platynkova-maska-na-oblicej-se-snecim-extraktem-jednorazova-maska",
            "price": "220",
            "categories": "[]",
            "manufacturer": "bioearth",
            "descriptionShort": "<p><strong>Typ pleti:</strong> všechny typy pleti, ideální pro dehydratovanou, unavenou, ochablou pleť, první vrásky, akné</p>",
            "description": "<p>Jednorázová plátýnková pleťová <strong>maska s vysokým obsahem mikrofiltrovaného šnečího extraktu (95%) a kyselinou hyaluronovou</strong> s vysokou a nízkou molekulovou hmotností, poskytuje pokožce maximální hydrataci, eliminuje první známky stárnutí, zpevňuje, vyhlazuje a celkově projasňuje. Šnečí extrakt je bohatý na látky nezbytné k uchování zdravé, krásné a mladé pleti jako je allantoin, elastin, kolagen, kys. glykolová, kys. mléčná, vitamíny a důležité minerály. Po aplikaci je pokožka viditelně hladší a pevnější. Pocit lehkosti a svěžesti přetrvává ještě dlouhou dobu po aplikaci.</p><p><em>Jak používat</em></p><p>masku aplikujte na dokonale čistou tvář (krásně přilne, nikde nestéká). Nechte působit 15-20 minut, poté odstraňte a zbylou tekutinu jemně vmasírujte do pleti do úplného vstřebání. Nesmývejte! Dle potřeby pro zvýšení účinku aplikujte <strong>příslušný krém z řady LOOM</strong>.<br /><strong>Původ:</strong> 100% italský původ<br /><strong>Metoda získávání:</strong> manuální stimulace – zdlouhavá, nákladná avšak bezpečná metoda respektující blaho hlemýžďů. Umožňuje získat vysoce kvalitní extrakt, hlemýžďům neubližuje a <br />ani je nestresuje.</p><p><em>Ingrediece</em><br />Aqua , Snail Secretion Filtrate, SACCHARIDE ISOMERATE, Sodium Hyaluronate, Avena sativa (Oat) bran extract*, VITIS VINIFERA (GRAPE) LEAF EXTRACT*, Erythritol, Glycerin, Xanthan Gum, PHENETHYL ALCOHOL, Caprylyl Glycol.</p><p><span style=\"font-size: 8pt;\">* Ingredience z ekologického zemědělství</span></p>",
            "image": "Biohearth/Loom_platynkova_maska_na_oblicej_se_snecim_extraktem.jpg",
            "additionalImages": "",
            "variants": "",
            "specifications": "[{\"title\":\"mnozstvi\",\"value\":\"15 ml\"}]",
            "published": "1",
            "created": "2022-03-13 10:57:06",
            "stockStatus": "skladem"
          },
          {
            "title": "Denní krém s mikrofiltrovaným extraktem ze šnečího slizu, Crème Suprême",
            "id": "denni-krem-s-mikrofiltrovanym-extraktem-ze-sneciho-slizu-creme-supreme",
            "price": "1290",
            "categories": "[]",
            "manufacturer": "bioearth",
            "descriptionShort": "",
            "description": "<p>Pleťový krém se silným tenzorovým efektem určený k ošetření pokožky vykazující první známky stárnutí. Obohacený o komplex oligopeptidů získávaných ze semen okra (Hibiscus aesculentus), bojuje proti tvorbě známek stárnutí. Má stahující účinky, takže pokožka je viditelně hladší, pevnější a kompaktnější.</p><p><em>Funkční látky</em><br />Mikrofiltrovaný extrakt ze šnečího slizu (77%), extrakt z ibišku, kyselina hyaluronová, výtažky z ovsa a měsíčku lékařského *.</p><p><em>Jak používat</em><br />Aplikujte přípravek na obličej a krk ráno a večer lehkou kruhovou masáží.</p>",
            "image": "Biohearth/Denni_krem_s_mikrofiltrovanym_extraktem_ze_sneciho_slizu_Creme_Supreme.jpg",
            "additionalImages": "",
            "variants": "",
            "specifications": "[{\"title\":\"mnozstvi\",\"value\":\"50 ml\"}]",
            "published": "1",
            "created": "2022-03-13 10:58:40",
            "stockStatus": "skladem"
          },
          {
            "title": "Cleansing milk (Odličovací, čistící mléko)",
            "id": "cleansing-milk-odlicovaci-cistici-mleko",
            "price": "410",
            "categories": "[\"physionatura-cleansing\"]",
            "manufacturer": "physio-natura",
            "descriptionShort": "",
            "description": "<p>Uklidňující a zvláčňující produkt šetrně a efektivně odstraňuje make-up i různé druhy nečistot, které na tváři v průběhu dne ulpí. Respektuje přirozenou úroveň hydratace a nenarušuje hydrolipidový film kůže. Díky unikátní receptuře umožňuje rychlou obnovu pleti. Pokožka je po použití čistá, jemná a vláčná na dotek. Mléko obsahuje hamamelis (Vilín), panthenol a heřmánkový extrakt, které pokožku regenerují, vyživují, zklidňují a posilují její přirozenou obranyschopnost.</p><p><strong>Vhodné pro:</strong> všechny typy pleti.</p><p><strong>Jak použít:</strong> naneste ráno a večer na ruce dostatečné množství na navlhčený obličej, oční kontury a krk. Krouživými pohyby tvář jemně masírujte po dobu 30 sekund, poté opláchněte důkladně teplou vodou, osušte a aplikujte příslušné pečující kroky Tonikum Cleansing, sérum a krém.</p><p><strong>TIP kosmetičky:</strong> Čištění je prvním a nejdůležitějším krokem v péči o pleť. Mléko nanášejte přímo na obličej, není zapotřebí používat vatový tamponek. Tato metoda je k pleti velmi šetrná a současně efektivní místo běžných vatových tamponků, které nasáknou velké množství produktu a pokožku může následné tření dráždit. Čištění zvyšuje účinek všech následně použitých produktů.</p>",
            "image": "PhysioNatura/Cleansing_milk-test.jpg",
            "additionalImages": "",
            "variants": "",
            "specifications": "[{\"title\":\"mnozstvi\",\"value\":\"250ml\"}]",
            "published": "1",
            "created": "2022-03-13 13:07:30",
            "stockStatus": "skladem"
          },
          {
            "title": "Bezalkoholové tonikum",
            "id": "bezalkoholove-tonikum",
            "price": "410",
            "categories": "[\"physionatura-cleansing\"]",
            "manufacturer": "physio-natura",
            "descriptionShort": "",
            "description": "<p>Tonik jde vždy ruku v ruce s odličovacím mlékem. Automaticky. Vždy. Jako šampón a kondicionér, nebo spíš hrnečky a podšálky, chcete-li. Patří k sobě a jen spolu dosáhnou kýženého efektu. Tento jemný tonik doslova přetéká vysokou koncentrací aktivních výtažků, <br />které způsobí, že Vaše pleť bude okouzlující.<br />Obsahuje destilovanou levandulovou vodu, která pleť hojí, zklidňuje a léčí akné. Pomerančové květy, které pomáhají vyrovnat produkci mazu, sjednocují tón pleti a rozzařujou ji. Navíc panthenol, který změkčuje pleť, zanechává ji vyhlazenou a navrací její přirozenou rovnováhu. Tonik pokožku dokonale připraví pro aplikaci séra a krému a díky změkčujícím schopnostem pomůže dostat aktivní látky ze séra a krému ještě hlouběji.</p><p><strong>TYP PLETI:</strong> pro všechny typy pleti i velmi citlivou.</p><p><strong>JAK POUŽÍT:</strong> Tonik přichází na řadu po hlavním čištění pleti (mléko / gel / pěna). Tonik naneste na vatový tamponek a lehce s ním pokožku obličeje a krku osvěžte. Tonik použijte jak večer, tak i samostatně ráno, pokožku po spánku osvěží a zbaví vyplavených toxinů, mazu a potu.<br /><strong>TIP KOSMETIČKY:</strong> Tonik lze aplikovat do dlaně, rozetřít na celý obličej a dlaněmi lehce do pokožky vtlačovat, můžete zapojit i prsty a lehce na obličej poklepávat (hra na piáno). Nic nepřijde nazmar a pokožce se tak dostane i lehké tlakové (akupresurní masáže).</p>",
            "image": "PhysioNatura/Bezalkoholove_tonikum.jpg",
            "additionalImages": "",
            "variants": "",
            "specifications": "[{\"title\":\"mnozstvi\",\"value\":\"250 ml\"}]",
            "published": "1",
            "created": "2022-03-13 13:10:58",
            "stockStatus": "skladem"
          },
          {
            "title": "Satinovací mořský peeling na obličej",
            "id": "satinovaci-morsky-peeling-na-oblicej",
            "price": "1300",
            "categories": "[\"physionatura-cleansing\"]",
            "manufacturer": "physio-natura",
            "descriptionShort": "",
            "description": "<p>Silný exfoliační peeling s krystaly ze soli z mrtvého moře. Speciálně vyvinut pro potřeby smíšené, mastné a problematické pleti. Má anti-aging efekt. Díky vysokému obsahu minerálů obnovuje buněčný metabolismus a regeneruje buněčnou strukturu pokožky. Může proto pomoct i v boji proti vráskám a ztrátě vlhkosti v pokožce. Obsahuje esenciální oleje ze sevilských pomerančů, levandule, citrónu a tymiánu. Tyto výjimečné složky mají protizánětlivé, hojivé a zvlhčující účinky. Pokožka je po použití jemná, vláčná, rozjasněná a vitální.</p><p><strong>TYP PLETI:</strong> smíšená, mastná a problematická pleť, akné.</p><p><strong>JAK POUŽÍT:</strong> Malé množství peelingu naneste na čistou a vlhkou (mokrou) pokožku obličeje, krku a dekoltu a jemnými krouživými pohyby masírujte, čím déle, tím lépe, alespoň do vstřebání materiálu,maximálně 8 minut. Poté důkladně smyjte vodou a naneste pečující sérum a/nebo krém. Používejte dle potřeby, ideálně 1x za 14 dní.</p><p><strong>TIP KOSMETIČKY:</strong> Peeling prováděný před aplikací pleťové masky umožňuje aktivním látkám působit hlouběji a intenzivněji. Výsledkem bude živější, sjednocená a přirozeně narůžovělá pokožka. Nebojte se použít na celé tělo, včetně podpaží a intimních partií (ne po depilaci).</p>",
            "image": "PhysioNatura/Satinovaci_morsky_peeling_na_oblicej.jpg",
            "additionalImages": "",
            "variants": "",
            "specifications": "[{\"title\":\"mnozstvi\",\"value\":\"250g\"}]",
            "published": "1",
            "created": "2022-03-13 13:16:16",
            "stockStatus": "skladem"
          },
          {
            "title": "ADUEO Odličovací pěna",
            "id": "adueo-odlicovaci-pena",
            "price": "720",
            "categories": "[\"physionatura-cleansing\"]",
            "manufacturer": "physio-natura",
            "descriptionShort": "",
            "description": "<p>Účinný okysličující čistící rituál, který velmi jemně a efektivně odstraní z pleti i ty nejodolnější nečistoty, make-up a znovu navrátí pleti tolik potřebnou rovnováhu.</p><p>Pěna má bohatou, krémovou a vzdušnou konzistenci a opojnou vůni. Obsahuje heřmánkový extrakt, který funguje skvěle nejen na zklidnění mysli, ale i na kožní vyrážky, akné a špatně se hojící rány. Kromě toho heřmánkový extrakt (na rozdíl od chemie a ropy) zabraňuje ucpávání pórů pokožky. Panthenol, který zlepšuje stav pleti poškozené ultrafialovým zářením, významně hydratuje a podporuje hojení, stimuluje i omlazení pleti. A olivový olej, který hydratuje. Kromě antioxidantů obsahuje olivový olej i skvalen, což je vysoce hydratační látka. A v neposlední řadě vyživuje: Vitamín A, D, K a E. Pěna Adueo je bohatá na povrchově aktivní látky přírodního původu na bázi cukru (bez SLS) se zklidňujícími vlastnostmi,  zvláště indikovaná  pro extrémně citlivou pleť.  Vhodná i pro miminka na mytí. Pěna je tvořena pumpičkou, stlačením, nikoliv chemicky.</p><p><strong>TYP PLETI:</strong> všechny typy pleti, doporučujeme pro normální, smíšenou i extrémně citlivou.</p><p><strong>JAK POUŽÍT:</strong> Naneste pěnu na již navlhčený obličej a jemně masírujte po dobu alespoň 30 sekund. Masáží dojde k uvolnění nečistot a zároveň se podpoří mikrocirkulace (prokrvení). Použijte ráno a / nebo večer. Důkladně opláchněte a pokračujte v běžné rutinní péči o pleť (tonikum, sérum a krém).</p><p><strong>TIP:</strong> ideální do sprchy</p>",
            "image": "PhysioNatura/ADUEO_Odlicovaci_pena.jpg",
            "additionalImages": "",
            "variants": "",
            "specifications": "[{\"title\":\"mnozstvi\",\"value\":\"150 ml\"}]",
            "published": "1",
            "created": "2022-03-13 13:18:34",
            "stockStatus": "skladem"
          },
          {
            "title": "Peeling z meruňkových jadrer ",
            "id": "peeling-z-merunkovych-jadrer",
            "price": "680",
            "categories": "[\"starway\"]",
            "manufacturer": "physio-natura",
            "descriptionShort": "",
            "description": "<p>Tento mléčný pleťový peeling obsahuje mikro částečky z meruňkových jader, které jemně odstraňují odumřelé kožní buňky a nečistoty. Pleť čistí, zjemňuje a vyhlazuje. </p><p><strong>TYP PLETI:</strong> všechny typy pleti.</p><p><strong>JAK POUŽÍT:</strong> malé množství peelingu naneste na vlhkou a čistou pokožku obličeje, krku a dekoltu a jemnými krouživými pohyby masírujte. Poté důkladně smyjte a naneste pečující sérum a/nebo krém. Používejte podle potřeby 1x za 14 dní.</p><p><strong>TIP KOSMETIČKY:</strong> Expres kosmetické ošetření. Naneste peeling večer na vlhkou a čistou pokožku obličeje, krku a dekoltu a jemnými krouživými pohyby masírujte. Poté důkladně smyjte a naneste pečující masku, masku nechte působit 10 minut, poté důkladně smyjte a naneste sérum a/nebo krém. Vaší pleti se tak dostane jedinečné péče jako v kosmetickém salónu a po probuzení bude jako znovu zrozená.</p>",
            "image": "PhysioNatura/Peeling_z_merunkovych_jadrer.jpg",
            "additionalImages": "",
            "variants": "",
            "specifications": "[{\"title\":\"mnozstvi\",\"value\":\"500 ml\"}]",
            "published": "1",
            "created": "2022-03-13 13:20:26",
            "stockStatus": "skladem"
          },
          {
            "title": "Arganovo - mandlový masážní olej",
            "id": "arganovo-mandlovy-masazni-olej",
            "price": "680",
            "categories": "[\"starway\"]",
            "manufacturer": "physio-natura",
            "descriptionShort": "",
            "description": "<p>Bohatý  masážní olej s nenasycenými mastnými kyselinami, které jsou důležité pro obnovu a regeneraci pokožky. Obsahuje arganový olej, který zbavuje pokožku přebytečného mazu, zpomaluje tvorbu vrásek a chrání před vlivy prostředí a času. Pokožku nemastí, ale zanechává hebkou a vláčnou.  Mandlový olej se řadí mezi nejcennější rostlinné oleje. Je výživný a vhodný pro všechny typy pleti. Pokožce dodává pocit hebkosti, mírní podráždění, chrání ji a pomáhá především suché kůži se sklony k olupování, svědění a popraskání. Slunečnicový olej, který má zvláčňující účinky, díky vysokému obsahu vitaminu E kůži výborně hojí a regeneruje. <br /><strong>TYP PLETI:</strong> všechny typy pleti.</p><p><strong>JAK POUŽÍT:</strong> malé množství oleje naneste na čistou pokožku obličeje, krku a dekoltu a jemnými krouživými pohyby masírujte.</p>",
            "image": "PhysioNatura/Arganovo_-_mandlovy_masazni_olej.jpg",
            "additionalImages": "",
            "variants": "",
            "specifications": "[{\"title\":\"mnozstvi\",\"value\":\"500 ml\"}]",
            "published": "1",
            "created": "2022-03-13 13:21:40",
            "stockStatus": "skladem"
          },
          {
            "title": "Krém na suché ruce",
            "id": "krem-na-suche-ruce",
            "price": "680",
            "categories": "[\"starway\"]",
            "manufacturer": "physio-natura",
            "descriptionShort": "",
            "description": "<p>Speciálně vyvinutý krém pro udržení mladé a krásné pokožky rukou bez pocitu mastnoty. Obsahuje olivový olej, který hydratuje a udržuje pokožku vláčnou a jemnou. Dále citronovou šťávu, vytamín E a panthenol, které udržují ruce revitalizované, vláčné a regenerují namáhanou pokožku rukou.  Krém je také ideální jako péče o nehty a nehtovou kůžičku.</p><p><strong>JAK POUŽÍT:</strong> aplikujte malé množství krému na hřbet ruky a lehce o sebe vmasírujte do pokožky rukou. Použijte kdykoli během dne dle potřeby, nebo po každém umytí.</p><p><strong>TIP KOSMETIČKY:</strong> Wellness pro Vaše ruce – ruce omyjte, osušte, aplikujte malé množství tělového peelingu a po dobu několika minut masírujte pokožku rukou. Peeling jemně odstraní odumřelé buňky kůže, obnoví, zjemní a vyhladí. Poté smyjte, na ještě vlhké ruce naneste 3 kapky arganovo-mandlového oleje Starway, vmasírujte. Věnujte pozornost nehtům i nehtové kůžičce, olej se krásně vstřebá. Na závěr naneste krém na ruce. Vaše ruce budou vyživené, krásné a hebké.</p>",
            "image": "PhysioNatura/Krem_na_suche_ruce.jpg",
            "additionalImages": "",
            "variants": "",
            "specifications": "[{\"title\":\"mnozstvi\",\"value\":\"500 ml\"}]",
            "published": "1",
            "created": "2022-03-13 13:23:21",
            "stockStatus": "skladem"
          },
          {
            "title": "Odličovací mléko s panthenolem",
            "id": "odlicovaci-mleko-s-panthenolem",
            "price": "680",
            "categories": "[\"starway\"]",
            "manufacturer": "physio-natura",
            "descriptionShort": "",
            "description": "<p>Toto bohaté mléko důkladně pokožku čistí, zanechává ji hladkou, čistou, hydratovanou a navozuje tak pocit dokonalého zklidnění a svěžesti.</p><p>Díky slunečnicovému oleji hydratuje, vyživuje, posiluje a má anti-agingové a antioxidační účinky. Extrakt z heřmánku má neobyčejné zklidňující a revitalizační účinky, je také ceněný pro své protizánětlivé, protialergenní účinky, navíc je analgetický a hojivý. Obsažená šťáva z Aloe vera pomáhá v pokožce udržet potřebnou hydrataci, díky čemuž ji chrání před vysušením a pocitem pnutí.</p><p><strong>TYP PLETI:</strong> pro všechny typy pleti, vhodná pro unavenou a zralou.</p><p><strong>JAK POUŽÍT:</strong> Aplikujte dostatečné množství na obličej, oční kontury a krk. Krouživými pohyby pokožku jemně masírujte. Provádějte čištění alespoň 30 sekund, poté smyjte důkladně vodou a osušte.</p><p><strong>TIP KOSMETIČKY:</strong> Čištění je prvním a nejdůležitějším krokem v péči o pleť. Jen čistá pleť je zdravá a krásná. Mléko nanášejte přímo na obličej, není zapotřebí používat vatový tamponek. Ten vsákne a spotřebuje velké množství mléka, navíc pokud je pokožka velmi citlivá, může ji tření tamponkem dráždit. Mléko dejte do dlaně, naneste na obličej a krk a provádějte lehounkou masáž. Nabalí se tak všechny nečistoty a zároveň tato jemná masáž aktivuje mikrocirkulaci. Po mléku vždy použijte tonik, který pokožku nejen dočistí, ale hlavně osvěží a změkčí, což pomáhá v penetraci účinných látek ze séra a krému hlouběji do pokožky. Pamatujte, že správné čištění zvyšuje účinek všech následně použitých produktů.</p>",
            "image": "PhysioNatura/Odlicovaci_mleko_s_panthenolem.jpg",
            "additionalImages": "",
            "variants": "",
            "specifications": "[{\"title\":\"mnozstvi\",\"value\":\"500 ml\"}]",
            "published": "1",
            "created": "2022-03-13 13:24:55",
            "stockStatus": "skladem"
          },
          {
            "title": "Tonikum s levandulí",
            "id": "tonikum-s-levanduli",
            "price": "680",
            "categories": "[\"starway\"]",
            "manufacturer": "physio-natura",
            "descriptionShort": "",
            "description": "<p>Tento jemný tonik doslova přetéká vysokou koncentrací aktivních výtažků, které způsobí, že Vaše pleť bude okouzlující.</p><p>Obsahuje květinové extrakty z levandule, která podporuje regeneraci pokožky, má dezinfekční a antibakteriální účinky, zklidňuje a uvolňuje napětí.<br />Výtažek hamamelis, Vilín je nesmírně oblíbená ingredience v produktech péče o pleť, zejména díky svým stahujícím a tonizačním účinkům. Navíc extrakt z medu udržuje pleť hydratovanou, reguluje pH pokožky a chrání buňky před poškozením.<br />Urea udržuje vyrovnané pH pokožky a napomáhá pronikání dalších účinných látek hluboko do pokožky. Váže na sebe velké množství vody a hydratuje pleť do hloubky bez zbytečného zatížení. Navíc kys. mléčná a citrónová pleť osvěžují, posilují a zachovávají elasticitu.<br />Tonik pokožku dokonale připraví pro aplikaci séra a krému a díky změkčujícím schopnostem pomůže dostat aktivní látky ze séra a krému ještě hlouběji.</p><p><strong>TYP PLETI:</strong> pro všechny typy pleti i velmi citlivou</p><p><strong>JAK POUŽÍT:</strong> Tonik přichází na řadu po hlavním čištění pleti (mléko / gel / pěna). Tonik naneste na vatový tamponek a lehce s ním pokožku obličeje a krku osvěžte. Tonik použijte jak večer, tak i samostatně ráno, pokožku po spánku osvěží a zbaví vyplavených toxinů, mazu a potu.</p><p><strong>TIP KOSMETIČKY:</strong> Tonik lze aplikovat do dlaně, rozetřít na celý obličej a dlaněmi lehce do pokožky vtlačovat, můžete zapojit i prsty a lehce na obličej poklepávat (hra na piáno). Nic nepřijde nazmar a pokožce se tak dostane i lehké tlakové (akupresurní masáže).</p>",
            "image": "PhysioNatura/Tonikum_s_levanduli.jpg",
            "additionalImages": "",
            "variants": "",
            "specifications": "[{\"title\":\"mnozstvi\",\"value\":\"500 ml\"}]",
            "published": "1",
            "created": "2022-03-13 13:25:53",
            "stockStatus": "skladem"
          },
          {
            "title": "Hydratační maska",
            "id": "hydratacni-maska",
            "price": "680",
            "categories": "[\"armonia\"]",
            "manufacturer": "physio-natura",
            "descriptionShort": "",
            "description": "<p>Čistící pleťová maska s jílem, hamamelis a panthenolem hloubkově čistí a obnovuje pleť. Absorbuje přebytečný maz a zjemňuje celkovou texturu pleti. Po použití okamžitě vidíte, že je pleť projasněná, čistá, jemná a vláčná. Obsahuje úžasné čistící, hojivé a obnovující látky.</p><p><strong>Vhodná pro:</strong> normální, smíšená, mastná a hrubá pleť, akné, ucpané póry, nadměrný lesk.</p><p><strong>Jak použít:</strong> Naneste na čistou tvář, nechte působit jen alespoň 8 minut. Poté důkladně opláchněte vodou. Na závěr naneste sérum a lehký hydratační krém.</p>",
            "image": "PhysioNatura/Hydratacni_maska.jpg",
            "additionalImages": "",
            "variants": "",
            "specifications": "[{\"title\":\"mnozstvi\",\"value\":\"125 ml\"}]",
            "published": "1",
            "created": "2022-03-13 13:27:37",
            "stockStatus": "skladem"
          },
          {
            "title": "Lehký hydratační krém",
            "id": "lehky-hydratacni-krem",
            "price": "620",
            "categories": "[\"armonia\"]",
            "manufacturer": "physio-natura",
            "descriptionShort": "",
            "description": "<p>Tento nadýchaný, lehký krém pokožku hydratuje, zjemňuje, chrání a hloubkově vyživuje, aniž by ji přesycoval. Obsahuje bílý jíl. Pleť bude krásně vyživená, zářivá, svěží a hebká zároveň. Bílý jíl je známý také pro své antibakteriální a protizánětlivé účinky. Při dlouhodobějším používání pomáhá regulovat tvorbu mazu a napomáhá ke zlepšení stavu pokožky, která trpí lupénkou, ekzémy či akné.</p><p><strong>TYP PLETI:</strong> Vhodný pro všechny typy pleti, ideální pro mladou se sklony k mastnotě.</p><p><strong>JAK POUŽÍT: </strong>Naneste ráno a večer na dokonale čistou pokožku obličeje a krku. Lehce vmasírujte. Okamžitě se vstřebá, nezanechá pocit těžkosti.</p>",
            "image": "PhysioNatura/Lehky_hydratacni_krem.jpg",
            "additionalImages": "",
            "variants": "",
            "specifications": "[{\"title\":\"mnozstvi\",\"value\":\"50 ml\"}]",
            "published": "1",
            "created": "2022-03-13 13:29:55",
            "stockStatus": "skladem"
          },
          {
            "title": "Krém na krk a dekolt",
            "id": "krem-na-krk-a-dekolt",
            "price": "915",
            "categories": "[\"energheia\"]",
            "manufacturer": "physio-natura",
            "descriptionShort": "",
            "description": "<p>Vitamín C je základní prvek pro lidské zdraví, široce využívaný v kosmetice pro své výjimečné omlazující a projasňující vlastnosti. Chrání před předčasným stárnutím, před volnými radikály, stimuluje tvorbu kolagenu a osvědčil se na projasnění a eliminaci tmavých skvrn (pigmentové, stařecké). Obsahuje ochranné faktory, melounový extrakt, panthenol a elastin.</p><p><strong>TYP PLETI: </strong>Vhodný pro všechny typy pleti, ideální pro unavenou a mdlou pleť nebo pro kuřáky.</p><p><strong>JAK POUŽÍT:</strong> Naneste ráno a večer na dokonale čistou pokožku obličeje a krku. Lehce vmasírujte. </p>",
            "image": "PhysioNatura/Krem_na_krk_a_dekolt.jpg",
            "additionalImages": "",
            "variants": "",
            "specifications": "[{\"title\":\"mnozstvi\",\"value\":\"50 ml\"}]",
            "published": "1",
            "created": "2022-03-13 13:31:44",
            "stockStatus": "skladem"
          },
          {
            "title": "Sérum s vit.C",
            "id": "serum-s-vit-c",
            "price": "900",
            "categories": "[\"energheia\"]",
            "manufacturer": "physio-natura",
            "descriptionShort": "",
            "description": "<p>Vitamín C je základní prvek pro lidské zdraví, široce využívaný v kosmetice pro své výjimečné omlazující a projasňující vlastnosti. Chrání před předčasným stárnutím, před volnými radikály, stimuluje tvorbu kolagenu a osvědčil se na projasnění a eliminaci tmavých skvrn (pigmentové, stařecké).</p><p><strong>Vhodný pro:</strong> unavená pleť bez jasu, vrásky, pigmentové skvrny, barevně nejednotná pleť.</p><p><strong>Jak použít:</strong> naneste 2 až 3 kapky na celou tvář včetně oblasti očního okolí/očních kontur, vyhněte se přímému kontaktu s očima. </p><p><strong>Upozornění:</strong> vyvarujte se přímému míchání s KYSELINOU GLYKOLOVOU 10% nebo oba produkty používejte odděleně. Pokud použijete také ZINEK + NIACINAMID 11% a PEPTIDY + IBIŠEK 2%, vždy až po VITAMINU C, ale ne smíchané dohromady.</p>",
            "image": "PhysioNatura/Serum_s_vit_C.jpg",
            "additionalImages": "",
            "variants": "",
            "specifications": "[{\"title\":\"mnozstvi\",\"value\":\"30ml\"}]",
            "published": "1",
            "created": "2022-03-13 13:34:04",
            "stockStatus": "skladem"
          },
          {
            "title": "Jemný odličovač očí",
            "id": "jemny-odlicovac-oci",
            "price": "480",
            "categories": "[rejuva]",
            "manufacturer": "physio-natura",
            "descriptionShort": "",
            "description": "<p>Delikátní oční odličovač, pro jemné a citlivé oblasti okolo očí. Pomáhá snižovat zarudnutí po odlíčení a zanechává pokožku svěží a odpočatou. Obsahuje bisabolol (hlavní složka silice z heřmánku lékařského), který má silné protizánětlivé a antimikrobiální vlastnosti.  100% účinky uvidíme tedy na pleti zánětlivé, mastící se, až aknózní. Pleť uklidňuje a regeneruje. Vhodný je také pro popraskané rty, ruce nebo chodidla. V kosmetice zlepší vstřebatelnost dalších látek. Pokožku vyhlazuje a dodá jí jemnost.</p>",
            "image": "PhysioNatura/Jemny_odlicovac_oci_200ml.jpg",
            "additionalImages": "",
            "variants": "",
            "specifications": "[{\"title\":\"mnozstvi\",\"value\":\"20 ml\"}]",
            "published": "1",
            "created": "2022-03-13 13:35:50",
            "stockStatus": "skladem"
          },
          {
            "title": "Lactica AHA čistící gel",
            "id": "lactica-aha-cistici-gel",
            "price": "760",
            "categories": "[\"lactica\"]",
            "manufacturer": "physio-natura",
            "descriptionShort": "",
            "description": "<p>Speciální jemný čistící gel, s pH 3,5 šetrně a efektivně čistí každodenní nečistoty, včetně make-upu. Kyselé pH zajistí, že při čištění nedojde k narušení ochranného filmu pokožky, respektuje její kyselý plášť. Perfektní pro použití samostatně nebo jako druhý krok při dvojitém čištění. Po použití je pleť čistá, vláčná, hebká na dotek. Obsahuje přírodní zklidňující a hojivé látky: extrakt z heřmánku a panthenol. Kyselinu mandlovou, mléčnou a glykolovou.</p><p><strong>Vhodný pro:</strong> normální, smíšená, mastná pleť, ucpané póry, akné, nadměrný lesk.</p><p><strong>Jak použít: </strong>Tvář navlhčete vodou, 1 až 2 pumpičky gelu naneste na tvář a proveďte jemnou masáž krouživými pohyby. Masáží dojde k uvolnění nečistot, pleť se hezky prokrví a podpoří se mikrocirkulace. Poté důkladně opláchněte vodou. V případě velkého líčení proveďte tento proces 2x. Na závěr naneste tonikum, sérum a krém, u mladé pleti postačí pouze krém.</p>",
            "image": "PhysioNatura/Lactica_AHA_cistici_gel_200ml.jpg",
            "additionalImages": "",
            "variants": "",
            "specifications": "[{\"title\":\"mnozstvi\",\"value\":\"200 ml\"}]",
            "published": "1",
            "created": "2022-03-13 13:37:57",
            "stockStatus": "skladem"
          },
          {
            "title": "Lactica AHA gel maska",
            "id": "lactica-aha-gel-maska",
            "price": "1000",
            "categories": "[\"lactica\"]",
            "manufacturer": "physio-natura",
            "descriptionShort": "",
            "description": "<p>Alfa-hydroxy kyseliny, nebo-li ovocné peelingy, nejsou v kosmetické péči nic nového. Už Kleopatra se koupala v mléce /kyselina mléčná/, Řekové ošetřovali popáleniny červeným vínem/kyselina vinná/ a pigmentové skvrny si odstraňovali citrónem/kyselina citronová/. Tyto ovocné kyseliny obsažené v řadě LACTICA byly vyvinuty tak, aby umožňovaly povrchovou exfoliaci pokožky, tzn. odstraňovaly odumřelé buňky a zároveň stimulovaly buněčné omlazení a obnovily pH pokožky tak, aby byla zdravá a zářivá.</p><p><strong>Vhodný pro:</strong> normální, smíšená, mastná pleť, ucpané póry, akné, nadměrný lesk.</p><p><strong>Jak použít:</strong> Naneste masku ve větší vrstvě a nechejte působit asi 10/15 minut. Odstraňte zbytky pomocí houbiček a vlažné vody a poté pokračujte v ošetření nanesením kyselého krému.</p>",
            "image": "PhysioNatura/Lactica_AHA_gel_maska.jpg",
            "additionalImages": "",
            "variants": "",
            "specifications": "[{\"title\":\"mnozstvi\",\"value\":\"250 ml\"}]",
            "published": "1",
            "created": "2022-03-13 13:38:58",
            "stockStatus": "skladem"
          },
          {
            "title": "Lactica AHA kyselý krém",
            "id": "lactica-aha-kysely-krem",
            "price": "820",
            "categories": "[\"lactica\"]",
            "manufacturer": "physio-natura",
            "descriptionShort": "",
            "description": "<p>Kyselý krém určený k podpoře hloubkového exfoliačního účinku pomocí AHA kyselin. Při respektování přirozené úrovně kyselosti pleti stimuluje tento krém tvorbu nových kožních buněk, což je velmi účinné při prevenci tvorby vrásek i akné.</p><p><strong>Vhodný pro:</strong> pro všechny typy pletí trpící suchostí až šupinatěním, dehydratací a  také pro pleť s rosaceou.</p><p><strong>Jak použít: </strong>Aplikujte výrobek po pečlivém čištění. Jemně masírujte krouživými pohyby, dokud se výrobek zcela nevstřebá.</p>",
            "image": "PhysioNatura/Lactica_AHA_kysely_krem.jpg",
            "additionalImages": "",
            "variants": "",
            "specifications": "[{\"title\":\"mnozstvi\",\"value\":\"50 ml\"}]",
            "published": "1",
            "created": "2022-03-13 13:40:59",
            "stockStatus": "skladem"
          },
          {
            "title": "Detoxikační jemný krém na kontury očí",
            "id": "detoxikacni-jemny-krem-na-kontury-oci",
            "price": "690",
            "categories": "[]",
            "manufacturer": "naobay",
            "descriptionShort": "",
            "description": "<p>Ultra čerstvá a účinná směs přísad, které omladí váš obličej a probudí vaše oči. Antioxidační pryskyřice dračího stromu se kombinuje s dekongestivním kofeinem k prevenci a opravě stárnutí pokožky. V jemné kontuře očí napraví unavený výraz. Receptura také obsahuje účinnou červenou mořskou řasu a aktivní složku Chilean Tara, která bude mít okamžitý liftingový efekt. Rovněž obsahuje kyselinu hyaluronovou, skvělý zvlhčovač, který také chrání před volnými radikály a zvyšuje koncentraci vnitřního kolagenu.<br />Vhodný pro všechny typy vzhledů a k použití na celý obličej, zvláště pokud je vaše pokožka citlivá nebo chcete extra antioxidační péči.</p><p><em>Jak používat</em><br />Naneste ráno a večer na oční okolí jemnými dotyky a dokončete krouživými pohyby pro úplné vstřebání. Lze použít na celý obličej.</p><p><em>Ingredience</em><br />Aqua, Aloe Barbadensis Leaf Juice*, Caprylic/capric triglyceride, Glycerin, Polyglyceryl-6 Distearate, Cetyl Alcohol, Vitis vinifera seed oil*, Coco-Caprylate/Caprate, Distarch Phosphate, PRUNUS ARMENIACA KERNEL OIL*, Butyrospermum parkii butter*, Punica Granatum Seed Oil*, JOJOBA ESTERS, Propanediol, Croton Lechleri Resin Extract, Coffea Arabica Seed Extract*, Glycyrrhiza Glabra Root Extract*, Caesalpinia spinosa fruit extract, Kappaphycus alvarezii extract, Avena Sativa Kernel Extract**, Sodium Hyaluronate, Kaolin, potassium sorbate, Sodium Benzoate, Benzyl Alcohol, Polyglyceryl-3 Beeswax, Dehydroacetic Acid, Xanthan Gum. </p><p>*Suroviny z ekologického zemědělství.</p><p>**Přírodní vůně (získané z esenciálních olejů).</p>",
            "image": "Naobay/Detoxikacni_jemny_krem_na_kontury_oci.jpg",
            "additionalImages": "",
            "variants": "",
            "specifications": "[{\"title\":\"mnozstvi\",\"value\":\"30 ml\"}]",
            "published": "1",
            "created": "2022-03-13 19:29:16",
            "stockStatus": "skladem"
          },
          {
            "title": "Omlazující denní krém ORIGIN",
            "id": "omlazujici-denni-krem-origin",
            "price": "1290",
            "categories": "[]",
            "manufacturer": "naobay",
            "descriptionShort": "",
            "description": "<p>Krém pro každodenní použití s ​​kyselinou hyaluronovou, která pomáhá hydratovat a chránit pokožku, v kombinaci s rýžovým olejem *, meruňkovým olejem * a tigernutovým olejem *, které dodávají hydratační mastné kyseliny a antioxidační vitamín E. Směs výtažků z jablek *, měsíčku *, maliny * a fialky *, které poskytují uklidňující a antioxidační vlastnosti. Ovesný extrakt **, působí jako napínák snižující expresní linie. Začlenění sladového extraktu nabízí vynikající zklidňující vlastnosti, zlepšuje expresi genů zapojených do bariérové ​​funkce, jakož i mechanismy reakce na stres a regeneraci a snižuje zarudnutí pokožky, pálení a štípání. Obsahuje pomerančovou květinovou vodu *, která dodává jemnost a svěžest.</p><p><br />* z ekologického zemědělství </p><p><br /><em>Jak používat</em><br />Naneste po očištění pokožky jemným masírováním, dokud se krém zcela nevstřebá. Používejte ve dne i v noci.</p><p><em>Ingredience</em><br />CITRUS AURANTIUM DULCIS FRUIT WATER*, Aqua , Coco-Caprylate/Caprate, Glycerin, Caprylic/capric triglyceride, Cetearyl Alcohol, Oryza Sativa Oil*, Polyglyceryl-6 Distearate, Cyperus Esculentus Root Oil*, PRUNUS ARMENIACA KERNEL OIL*, POLYGLYCERYL-10 STEARATE, Hydrolyzed Hyaluronic Acid, Rubus Idaeus Fruit Extract*, Viola Odorata Flower/Leaf Extract*, Pyrus Malus Fruit Extract*, Calendula officinalis flower extract*, Hordeum Vulgare Seed Extract, Avena Sativa Kernel Extract**, Benzyl Alcohol, Dehydroacetic Acid, potassium sorbate, Xanthan Gum, Parfum, Citric Acid, Limonene, Linalool. </p><p>*Suroviny z ekologického zemědělství.</p><p>**Vyrobeno za použití přírodních ingrediencí. Přírodní parfemace (získaná z přírodních esenciálních olejů). Díky přírodním složkám obsažených v krémech, či sérech od Naobay, může docházet ke změně barvy, struktuře, nebo vůni. Nemá to však žádný negativní vliv na kvalitu produktu.</p>",
            "image": "Naobay/Omlazujici_denni_krem_ORIGIN.jpg",
            "additionalImages": "",
            "variants": "",
            "specifications": "[{\"title\":\"mnozstvi\",\"value\":\"50 ml\"}]",
            "published": "1",
            "created": "2022-03-13 19:31:00",
            "stockStatus": "skladem"
          },
          {
            "title": "Lehký okysličující krém DETOX",
            "id": "lehky-okyslicujici-krem-detox",
            "price": "890",
            "categories": "[]",
            "manufacturer": "naobay",
            "descriptionShort": "",
            "description": "<p>Lehká emulze, která pokožku hydratuje, aniž by ji nasytila. Antioxidační síla zeleného čaje se spojí s ochrannými vlastnostmi legendární živoucí fosílií ginkgo biloba, která působí jako štít proti každodenním agresím (znečištění, volné radikály a vnitřní prostředí), zatímco malina bude chránit pokožku před ztrátou vody a aloe vera zklidní a zjemní.<br />Doporučeno pro pleť, která hledá lehký pocit pokožky.</p><p><em>Jak používat</em></p><p>Naneste po očištění pokožky jemným masírováním, dokud se krém zcela nevstřebá. Používejte ve dne i v noci.</p><p><em>Ingredience</em><br />Aqua, Aloe Barbadensis Leaf Juice*, Glycerin, Isoamyl Cocoate, Simmondsia chinensis seed oil*, Coco-Caprylate/Caprate, Caprylic/capric triglyceride, POLYGLYCERYL-3 DICITRATE/STEARATE, Cetearyl Alcohol, PRUNUS AMYGDALUS DULCIS OIL*, Vitis vinifera seed oil*, Propanediol, Ginkgo Biloba Leaf Extract*, Camellia Sinensis Leaf Extract*, Rubus Idaeus Fruit Extract*, Salvia Sclarea Extract*, potassium sorbate, Sodium Benzoate, Benzyl Alcohol, Dehydroacetic Acid, Xanthan Gum, Parfum**.</p><p>*Suroviny z ekologického zemědělství</p><p>**Přírodní vůně (získané z esenciálních olejů)</p>",
            "image": "Naobay/Lehky_okyslicujici_krem_DETOX.jpg",
            "additionalImages": "",
            "variants": "",
            "specifications": "[{\"title\":\"mnozstvi\",\"value\":\"50 ml\"}]",
            "published": "1",
            "created": "2022-03-13 19:32:34",
            "stockStatus": "skladem"
          },
          {
            "title": "Extra výživný krém DETOX",
            "id": "extra-vyzivny-krem-detox",
            "price": "990",
            "categories": "[]",
            "manufacturer": "naobay",
            "descriptionShort": "",
            "description": "<p>Kombinace nabitá výživnými organickými oleji a bambuckým máslem pro hloubkovou výživu a obnovu pokožky. Jeho vzorec obsahuje zázvorový extrakt s vlastnostmi proti stárnutí, který je doplněn o osvětlovací sílu lékořice, což má za následek zářivou a rovnoměrněji vypadající pokožku. Brusinka bude hloubkově hydratovat a zklidní a uvolní nejvíce namáhanou pokožku.<br />Doporučeno pro žíznivou pokožku, která chce v pokožce pocit hluboké výživy.</p><p><em>Jak používat</em></p><p>Naneste po očištění pokožky jemným masírováním, dokud se krém zcela nevstřebá. Můžete také nanést silnější vrstvu krému ve formě masky, která se přes noc vstřebá jako intenzivní ošetření proti stárnutí a výživě. Používejte ve dne i v noci.</p><p><em>Ingredience</em><br />Aqua, Aloe Barbadensis Leaf Juice*, Coco-Caprylate/Caprate, Glycerin, Glyceryl Stearate, OLEA EUROPAEA FRUIT OIL*, Caprylic/capric triglyceride, Cetearyl Alcohol, Stearyl Alcohol, Persea gratissima oil*, Butyrospermum parkii butter*, Sodium stearoyl lactylate, Propanediol, Zingiber officinale Root Extract*, Vaccinium myrtillus Leaf Extract, Croton Lechleri Resin Extract, Glycyrrhiza Glabra Root Extract*, Citrus Limon Fruit Extract*, potassium sorbate, Sodium Benzoate, Benzyl Alcohol, Dehydroacetic Acid, Xanthan Gum, Citric Acid, Parfum**.</p><p>*Suroviny z ekologického zemědělství.</p><p>**Přírodní vůně (získané z esenciálních olejů).</p>",
            "image": "Naobay/Extra_vyzivny_krem_DETOX.jpg",
            "additionalImages": "",
            "variants": "",
            "specifications": "[{\"title\":\"mnozstvi\",\"value\":\"50 ml\"}]",
            "published": "1",
            "created": "2022-03-13 19:33:59",
            "stockStatus": "skladem"
          },
          {
            "title": "Čistící pěna DETOX",
            "id": "cistici-pena-detox",
            "price": "530",
            "categories": "[]",
            "manufacturer": "naobay",
            "descriptionShort": "",
            "description": "<p>Okysličující čisticí rituál k odstranění nejodolnějších nečistot a vyvážení pokožky. S krémovou a mýdlovou texturou je její pěna plná zázvorového extraktu, který zlepšuje prokrvení pokožky a uklidňuje ji, zatímco svíravý citron má na starosti kontrolu nadbytečného kožního mazu a lesku. Zelený čaj chrání pokožku před oxidací a stárnutím.<br />Doporučeno pro pokožku, která má pocit hlubšího čištění pokožky.</p><p><em>Jak používat</em></p><p>Naneste přiměřené množství na dlaň a jemnou masáží rozetřete přípravek na navlhčený obličej. Opláchněte vodou a osušte bez tření.</p><p><em>Ingredience</em></p><p>Aqua, Ammonium Lauryl Sulfate, Aloe Barbadensis Leaf Juice*, Lauryl glucoside, Glycerin, CITRUS AURANTIUM DULCIS FRUIT WATER*, Citrus Limon Fruit Extract*, Camellia Sinensis Leaf Extract*, Zingiber officinale Root Extract*, potassium sorbate, Sodium Benzoate, Benzyl Alcohol, Dehydroacetic Acid, Parfum**</p><p>*Suroviny z ekologického zemědělství.</p><p><br />**Přírodní parfemace (získaná z přírodních esenciálních olejů).</p>",
            "image": "Naobay/Cistici_pena_DETOX.jpg",
            "additionalImages": "",
            "variants": "",
            "specifications": "[{\"title\":\"mnozstvi\",\"value\":\"150 ml\"}]",
            "published": "1",
            "created": "2022-03-13 19:35:15",
            "stockStatus": "skladem"
          },
          {
            "title": "Čistící pleťové mléko ORIGIN",
            "id": "cistici-pletove-mleko-origin",
            "price": "590",
            "categories": "[]",
            "manufacturer": "naobay",
            "descriptionShort": "",
            "description": "<p>Čisticí pleťové mléko, které hloubkově vyčistí vaši pokožku a zanechá ji jemnou, čistou a hydratovanou díky čisticím olejům, jako je dýňový olej *, olivový olej *, tygří ořech *a rýžový olej *, které poskytují vlastnosti proti stárnutí a antioxidační vlastnosti.</p><p>Toto čisticí mléko mísí zklidňující a uklidňující vlastnosti extraktu z organické Violet * s hydratačním a antioxidačním působením výtažků z Apple * a Lemon *. Obsahuje také pomerančovou květovou vodu *, která dodává jemnost a svěžest.</p><p><em>Jak používat</em></p><p><strong>TIP KOSMETIČKY: </strong><br />Mléko nanášejte na navlhčené ruce, není zapotřebí používat vatový tamponek.<br />Ten vsákne a spotřebuje velké množství mléka, navíc může tření tamponkem dráždit obličej a celkově může být celá procedura nepříjemná. Pokud máte i tak potřebu použít tamponek, namočte ho do vody a vymáčkněte z něj přebytečnou vodu. Mléko dejte do dlaně, naneste na obličej a krk a provádějte lehounkou masáž. Nabalí se tak všechny nečistoty a zároveň tato jemná masáž aktivuje mikrocirkulaci. Poté setřete navlhčeným tamponky, nebo jen samotnou vodou. Jestli jste výrazněji nalíčená opakujte proces 2x, 3x..</p><p>Po mléku vždy použijte tonik, který pokožku nejen dočistí, ale hlavně osvěží a změkčí, vyrovná pH, což pomáhá v penetraci účinných látek ze séra a krému hlouběji do pokožky. </p><p>V zahraničí si ženy automaticky kupují vždy naráz pleťové mléko a tonik. Nebo pak - sérum a pleťový krém, vědí, že tyto produkty jsou nerozlučná dvojka a jeden s druhým vytvářejí synergii.</p><p><em>Ingredience</em><br />Aqua, CITRUS AURANTIUM DULCIS FRUIT WATER*, Aloe Barbadensis Leaf Juice*, Coco-Caprylate/Caprate, OLEA-EUROPAEA-FRUIT-OIL*, Caprylic/capric triglyceride, Glycerin, POLYGLYCERYL-3 DICITRATE/STEARATE, Cucurbita Pepo Seed Oil*, Glyceryl Stearate, Cyperus Esculentus Root Oil*, Oryza Sativa Oil*, Stearyl Alcohol, Viola Odorata Flower/Leaf Extract*, Pyrus Malus Fruit Extract*, Citrus Limon Fruit Extract*, Benzyl Alcohol, Dehydroacetic Acid, potassium sorbate, Sodium Benzoate, Xanthan Gum, Citric Acid, Parfum**, Citral**, Geraniol**, Limonene**, Linalool**.</p><p>*Suroviny z ekologického zemědělství.</p><p>**Přírodní parfemace (získané z přírodních esenciálních olejů). Díky přírodním složkám obsažených v krémech, či sérech od Naobay, může docházet ke změně barvy, struktuře, nebo vůni. Nemá to však žádný negativní vliv na kvalitu produktu.</p>",
            "image": "Naobay/Cistici_pletove_mleko_ORIGIN.jpg",
            "additionalImages": "",
            "variants": "",
            "specifications": "[{\"title\":\"mnozstvi\",\"value\":\"200 ml\"}]",
            "published": "1",
            "created": "2022-03-13 19:36:29",
            "stockStatus": "skladem"
          },
          {
            "title": "Čisticí pleťové tonikum",
            "id": "cistici-pletove-tonikum",
            "price": "370",
            "categories": "[]",
            "manufacturer": "naobay",
            "descriptionShort": "",
            "description": "<p>V tomto toniku je koncentrována aktivní pumpa, která přinese vaší kůži veškerý půvab. Obsahuje hydrolyzované bílkoviny z rýže, malinového extraktu *, altea * a měsíčku, aniž byste zapomněli na květinovou pomerančovou vodu, která dodává vaší pokožce hebkost a svěžest.<br />Extrakt z maliníku * působí díky obsahu vitaminu C jako antioxidant a proti volným radikálům. Altea * zklidňuje a chrání pokožku před vnějšími agresemi a bojuje proti degradaci přírodní kyseliny hyaluronové obsažené v pokožce. Extrakt z měsíčku * hydratuje a zklidňuje pokožku.</p><p><em>Jak používat</em><br />Aplikujte pomocí vatového tamponku, jemně masírujte, aby se tonikum rovnoměrně rozprostřelo po pokožce. Může být použit jako závěrečná fáze čištění pleti, nebo s úplně vyčištěnou pletí jako koktejl účinných látek.<br /><br /><em>Ingredience</em><br />Aqua, CITRUS AURANTIUM DULCIS FRUIT WATER*, Glycerin, Propanediol, Lavandula Angustifolia Flower Water*, Mentha Sativa Leaf Water*, Hydrolyzed Rice Protein, Rubus Idaeus Fruit Extract*, Helichrysum Stoechas Flower Extract*, Althaea officinalis Root Extract*, Calendula officinalis flower extract*, potassium sorbate, Sodium Benzoate, Cellulose gum, Citric Acid, Parfum**, Citral, Geraniol, Linalool. </p><p>*Suroviny z ekologického zemědělství.</p><p>**Přírodní parfemace (získané z přírodních esenciálních olejů). Díky přírodním složkám obsažených v krémech, či sérech od Naobay, může docházet ke změně barvy, struktuře, nebo vůni. Nemá to však žádný negativní vliv na kvalitu produktu.</p>",
            "image": "Naobay/Cistici_pletove_tonikum.jpg",
            "additionalImages": "",
            "variants": "",
            "specifications": "[{\"title\":\"mnozstvi\",\"value\":\"200 ml\"}]",
            "published": "1",
            "created": "2022-03-13 19:38:31",
            "stockStatus": "skladem"
          },
          {
            "title": "Hydratační a zklidňující  krém s kys.hyaluronovou",
            "id": "hydratacni-a-zklidnujici-krem-s-kys-hyaluronovou",
            "price": "590",
            "categories": "[]",
            "manufacturer": "naobay",
            "descriptionShort": "",
            "description": "<p>Hluboce hydratační a zklidňující krém na obličej. Formulováno s výtažkem Centella Asiatica, mořskými řasami a kyselinou hyaluronovou, poskytuje intenzivní pohodlí.</p><p><em>Jak používat</em></p><p>Naneste na obličej prsty a masírujte, dokud se úplně nevstřebá.</p><p><br /><em>Ingredience</em><br />Aqua, Aloe Barbadensis Leaf Juice*, Caprylic/capric triglyceride, OLEA EUROPAEA FRUIT OIL*, Glycerin, Polyglyceryl 3 Dicitrate/Stearate, Butyrospermum parkii butter*, ARGANIA SPINOSA KERNEL OIL*, Glyceryl Stearate, Stearyl Alcohol, Centella Asiatica Extract, Lithothamnion calcareum extract, Simmondsia chinensis seed oil*, Vaccinium myrtillus Leaf Extract, Hydrolyzed Hyaluronic Acid, Sodium Hyaluronate, Lactic acid, Amylopectin, Spirulina Platensis Extract, Trehalose, Xanthan Gum, SODIUM CITRATE, Sodium Benzoate, potassium sorbate, Dehydroacetic Acid, Citric Acid, Parfum**, BENZYL SALICYLATE**,Limonene**,Linalol**</p><p>* Suroviny z ekologického zemědělství</p><p>** Parfém obsažený v produktu je přírodního původu</p>",
            "image": "Naobay/Hydratacni_a_zklidnujici_krem_s_kys.hyaluronovou.jpg",
            "additionalImages": "",
            "variants": "",
            "specifications": "[{\"title\":\"mnozstvi\",\"value\":\"50 ml\"}]",
            "published": "1",
            "created": "2022-03-13 19:40:45",
            "stockStatus": "skladem"
          },
          {
            "title": "Omlazující regenerační pleťové sérum (DEN A NOC)",
            "id": "omlazujici-regeneracni-pletove-serum-den-a-noc",
            "price": "1490",
            "categories": "[]",
            "manufacturer": "naobay",
            "descriptionShort": "",
            "description": "<p>Toto sérum ve své formulaci kombinuje molekuly kyseliny hyaluronové, které pomáhají hydratovat a zadržovat vodu v pokožce spolu se silnou přírodní molekulou s vápníkem, která aktivuje přirozenou syntézu kyseliny hyaluronové a elastinu.<br />Kromě toho ve svém složení najdete rýžový olej *, meruňkový olej *a tygří olej *, které dodávají hydratační mastné kyseliny a antioxidační vitamín E a výtažky z heřmánku *, lékořice *, citronu *, maliny *a fialky *pro zlepšení hydratace a účinek stárnutí séra.<br />Obsahuje pomerančovou květovou vodu *, která dodává jemnost a svěžest, a výtažek z ovsa **, který působí jako zpevňovač a redukuje výrazové linky.</p><p><em>Jak používat</em><br />Naneste a rozetřete jemnou masáží, dokud se zcela nevstřebá.</p><p><em>Ingredience</em><br />CITRUS AURANTIUM DULCIS FRUIT WATER*, Aqua (Voda), Glycerin, PRUNUS ARMENIACA KERNEL OIL*, Decyl Cocoate, Cyperus Esculentus Root Oil*, Oryza Sativa Oil*, Stearyl Alcohol, Polyglyceryl-2-Stearate, Avena Sativa Kernel Extract**, Glyceryl Stearate, Hydrolyzed Hyaluronic Acid, Kalcium Ketogluconate, CHAMOMILLA RECUTITA FLOWER EXTRACT*, Glycyrrhiza Glabra Root Extract*, Citrus Limon Fruit Extract*, Rubus Idaeus Fruit Extract*, Viola Odorata Flower/Leaf Extract*, potassium sorbate, Benzyl Alcohol, Sodium Benzoate, Xanthan Gum, Citric Acid, Parfum, Citral, Geraniol, Limonene, Linalool. </p><p>*Suroviny z ekologického zemědělství.</p><p>**Vyrobeno pomocí přírodních ingrediencí. Přírodní parfemace (získaná z přírodních esenciálních olejů). Díky přírodním složkám obsažených v krémech, či sérech od Naobay, může docházet ke změně barvy, struktuře, nebo vůni. Nemá to však žádný negativní vliv na kvalitu produktu</p>",
            "image": "Naobay/Omlazujici_regeneracni_pletove_serum_(DEN_A_NOC).jpg",
            "additionalImages": "",
            "variants": "",
            "specifications": "[{\"title\":\"mnozstvi\",\"value\":\"30 ml\"}]",
            "published": "1",
            "created": "2022-03-13 19:44:46",
            "stockStatus": "skladem"
          },
          {
            "title": "Černá maska s fosilním dřevem",
            "id": "cerna-maska-s-fosilnim-drevem",
            "price": "690",
            "categories": "[]",
            "manufacturer": "naobay",
            "descriptionShort": "",
            "description": "<p>Hluboká detoxikační kúra k odstranění městského znečištění a hromadění nečistot z každého póru pokožky. Obsahuje aktivní uhlí, silný čisticí prostředek, který vyvažuje tažením přebytečného mazu a bakterií, podporuje redukci černých teček a zářivější a jednotnější pleť. Lékořice a zelený čaj s antioxidačními vlastnostmi, budou chránit pokožku před volnými radikály.<br />Doporučeno pro pokožku, která touží po obnově pocitu hluboké hygieny. Důrazně se doporučuje zejména pro pokožku se sklonem k akné a mastné pleti.</p><p><em>Jak používat</em><br />Naneste rovnoměrnou vrstvu na čistou a suchou pokožku a nechte působit 10 až 20 minut. Opláchněte velkým množstvím vody. Doporučuje se používat jednou týdně.</p><p><em>Ingredience</em><br />Aqua, Bentonite, Aloe Barbadensis Leaf Juice*, Glycerin, Polyglyceryl-2 Stearate, Charcoal Powder, Glyceryl Stearate, Stearyl Alcohol, Diatomaceous Earth, Camellia Sinensis Leaf Extract*, Glycyrrhiza Glabra Root Extract*, Pyrus Malus Fruit Extract, potassium sorbate, Sodium Benzoate, Benzyl Alcohol, Dehydroacetic Acid, Xanthan Gum, Parfum**.</p><p><br />*Suroviny z ekologického zemědělství</p><p>**Přírodní vůně (získané z esenciálních olejů)</p>",
            "image": "Naobay/Cerna_maska_s_fosilnim_drevem.jpg",
            "additionalImages": "",
            "variants": "",
            "specifications": "[{\"title\":\"mnozstvi\",\"value\":\"75 ml\"}]",
            "published": "1",
            "created": "2022-03-13 19:46:47",
            "stockStatus": "skladem"
          },
          {
            "title": "Multifunkční čistící gel pro muže",
            "id": "multifunkcni-cistici-gel-pro-muze",
            "price": "439",
            "categories": "[]",
            "manufacturer": "naobay",
            "descriptionShort": "",
            "description": "<p>Tento přírodní BEZSULFÁTOVÝ obličejový gel šetrně čistí a chrání pleť.<br />Obsahuje extrakty z máty a jinanu dvoulaločného, které čistí a stimulují pleť, zanechávají ji svěží a pevnou. Extrakty z měsíčku lékařského, lékořice a kávy navíc zklidňují a revitalizují. Bohatá pěna jemně čistí a udržuje přirozené pH pokožky.</p><p><em>Jak používat</em></p><p>Na navlhčený obličej naneste malé množství gelu a konečky prstů jemně vmasírujte do pokožky obličeje a krku, abyste odstranili nečistoty. Smyjte dostatečným množstvím vody a osušte.</p><p><em>Ingredience</em></p><p>Aqua, Sodium Cocoamphoacetate, Cocamidopropyl Betaine, Aloe Barbadensis Leaf Juice*, Disodium Lauryl Sulfosuccinate, Glycerin, Mentha Piperita Leaf Water*, Glycyrrhiza Glabra Root Extract*, Mentha Piperita Leaf Extract*, Coffea Arabica Seed Extract*, Calendula officinalis flower extract*, Ginkgo Biloba Leaf Extract*, Sorbitan Sesquicaprylate, Propanediol, potassium sorbate, Sodium Benzoate, Sodium Levulinate, Citric Acid, Parfum**, Limonene**, Linalool**.</p><p>*Suroviny z ekologického zemědělství.</p><p>**Přírodní parfemace (získaná z přírodních esenciálních olejů). Díky přírodním složkám obsažených v krémech, či sérech od Naobay, může docházet ke změně barvy, struktuře, nebo vůni. Nemá to však žádný negativní vliv na kvalitu produktu.</p>",
            "image": "Naobay/Multifunkcni_cistici_gel_pro_muze.jpg",
            "additionalImages": "",
            "variants": "",
            "specifications": "[{\"title\":\"mnozstvi\",\"value\":\"100 ml\"}]",
            "published": "1",
            "created": "2022-03-13 19:48:46",
            "stockStatus": "skladem"
          },
          {
            "title": "Tonizační pleťová mlha",
            "id": "tonizacni-pletova-mlha",
            "price": "370",
            "categories": "[]",
            "manufacturer": "naobay",
            "descriptionShort": "",
            "description": "<p>Tonizační pleťová mlha je osvěžující koktejl vitamínů, který hloubkově hydratuje, zklidňuje, rozjasňuje, harmonizuje a chrání. Mlha oživí a nastartuje pleť po probuzení, výjimečně zklidní a harmonizuje pH po čištění. Též výborně zafixuje a oživí make-up a to kdykoliv v průběhu dne.<br />Osvěžující ovocná šťáva z aloe vera*, extrakt z jablka*, z listů borůvek* a zelený čaj, právě to navrátí Vaši pleť zpátky k životu.</p><p><em>Jak používat</em></p><p>Mlhu můžete použít ráno pro osvěžení, večer po hlavním čističi pro regulaci pH (mléko, pěna, olej…) a dle potřeby i kdykoliv v průběhu dne pro osvěžení.</p><p>Rozprašovač zmáčkněte až nad doraz na vzdálenost natažené ruky od tváře (zavřete oči). Zahalí Vás příjemná, osvěžující a voňavá mlha. Pokud použijete mlhu jako tonikum k dočištění nečistot (po odličovacím mléku či pěně) – nastříkejte na navlhčený vatový tamponek a jemně obličej přetřete. Výborná do klimatizovaných a přetopených prostor.</p><p><em>Ingredience</em><br />Aqua , Aloe Barbadensis Leaf Juice*, Glycerin, Propanediol, Vaccinium myrtillus Leaf Extract, Pyrus Malus Fruit Extract*, Camellia Sinensis Leaf Extract*, Sodium Hyaluronate, Glycyrrhiza Glabra Root Extract*, Salvia Sclarea Extract*, Sodium Levulinate, Decyl Glucoside, SODIUM PHYTATE, potassium sorbate, Sodium Benzoate, Parfum (Fragrance)** <br />*Suroviny z ekologického zemědělství<br />**Přírodní vůně</p>",
            "image": "Naobay/Tonizacni_pletova_mlha.jpg",
            "additionalImages": "",
            "variants": "",
            "specifications": "[{\"title\":\"mnozstvi\",\"value\":\"200 ml\"}]",
            "published": "1",
            "created": "2022-03-13 19:50:11",
            "stockStatus": "skladem"
          },
          {
            "title": "Krém na ruce s pomerančovým extraktem",
            "id": "krem-na-ruce-s-pomerancovym-extraktem",
            "price": "290",
            "categories": "[]",
            "manufacturer": "naobay",
            "descriptionShort": "",
            "description": "<p>Speciálně vyvinutý krém pro udržení mladé a krásné pokožky rukou bez pocitu mastnoty. Obsahuje bambucké máslo*, které hydratuje a udržuje pokožku vláčnou a jemnou. Dále pomerančovou šťávu, výtažky z heřmánku* a Aloe Vera*, které udržují ruce revitalizované, vláčné a regenerují namáhanou pokožku rukou. Heřmánek* má neobyčejné zklidňující a revitalizační účinky, je také ceněný pro své protizánětlivé, protialergenní účinky, navíc je analgetický a hojivý. Obsažená šťáva z Aloe vera* pomáhá v pokožce udržet potřebnou hydrataci, díky čemuž ji chrání před vysušením a pocitem pnutí.<br />Krém je také ideální jako péče o nehty a nehtovou kůžičku.</p><p><em>Ingredience</em><br />Aqua, Aloe Barbadensis Leaf Juice*, OLEA EUROPAEA FRUIT OIL*, Caprylic/capric triglyceride, Glycerin, Coco-Caprylate Caprate, Methyl Glucose Sesquistearate, GlycerylStearate, Stearyl Alcohol, Butyrospermum parkii butter*, Persea gratissima oil*, Citrus Aurantium Dulcis Fruit Extract*, Citrus Sinensis Oil*, CHAMOMILLA RECUTITA FLOWER EXTRACT*, Benzyl Alcohol, potassium sorbate, Sodium Benzoate, Dehydroacetic Acid, Citric Acid.</p><p>*Ingredience pocházející z ekologického zemědělství. Díky přírodním složkám obsažených v krémech, či sérech od Naobay, může docházet ke změně barvy, struktuře, nebo vůni. Nemá to však žádný negativní vliv na kvalitu produktu.</p>",
            "image": "Naobay/Krem_na_ruce_s_pomerancovym_extraktem.jpg",
            "additionalImages": "",
            "variants": "",
            "specifications": "[{\"title\":\"mnozstvi\",\"value\":\"100 ml\"}]",
            "published": "1",
            "created": "2022-03-13 19:51:39",
            "stockStatus": "skladem"
          }
    ]';
}
?>